name: bump version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Print version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}
