name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy

    - name: Type checking
      run: mypy .

    - name: Run commit message linter
      uses: wagoid/commitlint-github-action@v6